# Generated by Django 4.2.7 on 2025-12-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('officer', 'Officer'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='applicant', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('passport-first', 'e-Passport First-Time'), ('passport-replacement', 'e-Passport Replacement'), ('nationalid-first', 'National ID First-Time'), ('nationalid-replacement', 'National ID Replacement')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('confirmation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('applicant_type', models.CharField(blank=True, choices=[('above18', 'Above 18'), ('below18', 'Below 18')], max_length=10, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('other_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('other_passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('place_of_residence', models.CharField(max_length=200)),
                ('birth_country', models.CharField(max_length=100)),
                ('birth_state', models.CharField(max_length=100)),
                ('birth_city', models.CharField(max_length=100)),
                ('passport_type', models.CharField(blank=True, choices=[('2-year', '2 Years'), ('5-year', '5 Years'), ('10-year', '10 Years')], max_length=10, null=True)),
                ('travel_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('replacement_reason', models.CharField(blank=True, choices=[('lost', 'Lost'), ('stolen', 'Stolen'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('correction', 'Correction')], max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/photos/')),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='documents/ids/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='documents/signatures/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/certificates/')),
                ('old_document', models.FileField(blank=True, null=True, upload_to='documents/old/')),
                ('police_report', models.FileField(blank=True, null=True, upload_to='documents/reports/')),
                ('civil_registry_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_pdf', models.FileField(blank=True, null=True, upload_to='approved_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confirmation_number'], name='application_confirm_e383d0_idx'), models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['application_type'], name='application_applica_80006e_idx'), models.Index(fields=['user'], name='application_user_id_9457c8_idx')],
            },
        ),
    ]
