# Generated by Django 4.2 on 2025-12-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_payment_method_application_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_proof_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
