# Generated by Django 4.2 on 2025-12-17 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_application_payment_proof_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Arabic translation of title', max_length=200)),
                ('content', models.TextField()),
                ('content_ar', models.TextField(blank=True, help_text='Arabic translation of content')),
                ('excerpt', models.CharField(help_text='Short summary for preview', max_length=300)),
                ('excerpt_ar', models.CharField(blank=True, help_text='Arabic translation of excerpt', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Arabic translation of title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, help_text='Arabic translation of description')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(blank=True, help_text='e.g., Events, Facilities, Staff', max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Arabic translation of title', max_length=200)),
                ('content', models.TextField()),
                ('content_ar', models.TextField(blank=True, help_text='Arabic translation of content')),
                ('excerpt', models.CharField(help_text='Short summary for preview', max_length=300)),
                ('excerpt_ar', models.CharField(blank=True, help_text='Arabic translation of excerpt', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('category', models.CharField(blank=True, help_text='e.g., Tips, Updates, Guides', max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
